' Generated by bmxlocale from the canonical English catalogue.
' Do not edit this file directly.

SuperStrict

Import BlitzMax.Locale

Const BLS_MSG_INSTALLED_MODULES_AMBIGUOUS_MODULE:Int = 1
Const BLS_MSG_PROTOCOL_MISSING_CONTENT_LENGTH_HEADER:Int = 2
Const BLS_MSG_STARTUP_STANDARD_IO_CONFIGURATION_FAILED:Int = 3

Type TBlsMessages
	Function InstalledModulesAmbiguousModule:TLocalisedMessage(moduleName:String, existingPath:String, discoveredPath:String)
		Return TLocalisedMessage.Create("bls", BLS_MSG_INSTALLED_MODULES_AMBIGUOUS_MODULE, "Ambiguous module '{moduleName}' maps to both '{existingPath}' and '{discoveredPath}'", [TMessageArg.Create("moduleName", moduleName), TMessageArg.Create("existingPath", existingPath), TMessageArg.Create("discoveredPath", discoveredPath)])
	End Function
	Function ProtocolMissingContentLengthHeader:TLocalisedMessage()
		Return TLocalisedMessage.Create("bls", BLS_MSG_PROTOCOL_MISSING_CONTENT_LENGTH_HEADER, "LSP message has no Content-Length header")
	End Function
	Function StartupStandardIoConfigurationFailed:TLocalisedMessage()
		Return TLocalisedMessage.Create("bls", BLS_MSG_STARTUP_STANDARD_IO_CONFIGURATION_FAILED, "Unable to configure byte-exact LSP standard I/O")
	End Function
End Type
