' Generated by bmxlocale from the canonical English catalogue.
' Do not edit this file directly.

SuperStrict

Import BlitzMax.Locale

Const LANGUAGE_MSG_PARSER_EXPRESSION_NESTING_TOO_DEEP:Int = 1
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION:Int = 2
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_IN_EXPRESSION:Int = 3
Const LANGUAGE_MSG_PARSER_EXPECTED_CLOSE_PARENTHESIS:Int = 4
Const LANGUAGE_MSG_PARSER_EXPECTED_QUALIFIED_SUPER_INTERFACE:Int = 5
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_FOUND_TOKEN:Int = 6
Const LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_ARGUMENTS:Int = 7
Const LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_INDEXES:Int = 8
Const LANGUAGE_MSG_CONSTANT_DIVISION_BY_ZERO:Int = 9
Const LANGUAGE_MSG_TYPE_EXPECTED_TYPE_ARGUMENTS:Int = 10
Const LANGUAGE_MSG_CONDITIONAL_EXPECTED_EXPRESSION:Int = 11
Const LANGUAGE_MSG_CONDITIONAL_UNEXPECTED_TOKEN:Int = 12
Const LANGUAGE_MSG_CONDITIONAL_EXPECTED_CLOSE_PARENTHESIS:Int = 13
Const LANGUAGE_MSG_CONDITIONAL_EXPECTED_OPERAND:Int = 14
Const LANGUAGE_MSG_PARSER_PARENTHESIZE_CALCULATED_FROM_END_ENDPOINT:Int = 15
Const LANGUAGE_MSG_PARSER_FROM_END_ENDPOINT_REQUIRES_RANGE:Int = 16
Const LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_SLICE:Int = 17
Const LANGUAGE_MSG_PARSER_POSTFIX_TYPE_REQUIRES_NUMERIC_LITERAL:Int = 18
Const LANGUAGE_MSG_PARSER_EXPECTED_TYPE_AFTER_NEW:Int = 19
Const LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_CONSTRUCTOR_ARGUMENTS:Int = 20
Const LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_ARRAY_LITERAL:Int = 21
Const LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_CAST:Int = 22
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_SOURCE_MODE:Int = 23
Const LANGUAGE_MSG_PARSER_VISIBILITY_ONLY_INSIDE_TYPE:Int = 24
Const LANGUAGE_MSG_PARSER_VISIBILITY_NOT_VALID_FOR_INTERFACE:Int = 25
Const LANGUAGE_MSG_PARSER_EXPECTED_ENUM_NAME:Int = 26
Const LANGUAGE_MSG_PARSER_EXPECTED_ENUM_UNDERLYING_TYPE:Int = 27
Const LANGUAGE_MSG_PARSER_EXPECTED_END_ENUM:Int = 28
Const LANGUAGE_MSG_PARSER_EXPECTED_ENUM_VALUE_NAME:Int = 29
Const LANGUAGE_MSG_PARSER_EXPECTED_CONSTANT_EXPRESSION_AFTER_EQUALS:Int = 30
Const LANGUAGE_MSG_PARSER_EXPECTED_LOOP_LABEL_NAME:Int = 31
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_LOOP_LABEL:Int = 32
Const LANGUAGE_MSG_PARSER_EXPECTED_END_IF:Int = 33
Const LANGUAGE_MSG_PARSER_EXPECTED_END_WHILE:Int = 34
Const LANGUAGE_MSG_PARSER_EXPECTED_REPEAT_TERMINATOR:Int = 35
Const LANGUAGE_MSG_PARSER_EXPECTED_NEXT:Int = 36
Const LANGUAGE_MSG_PARSER_EXPECTED_FOR_LOOP_HEADER:Int = 37
Const LANGUAGE_MSG_PARSER_EXPECTED_EQUALS_IN_FOR_LOOP_HEADER:Int = 38
Const LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_LOOP_VARIABLE_BEFORE_EQUALS:Int = 39
Const LANGUAGE_MSG_PARSER_EXPECTED_LOOP_TARGET_BEFORE_EQUALS:Int = 40
Const LANGUAGE_MSG_PARSER_EXPECTED_FOR_LOOP_CLAUSE:Int = 41
Const LANGUAGE_MSG_PARSER_EACH_IN_MUST_FOLLOW_EQUALS:Int = 42
Const LANGUAGE_MSG_PARSER_EXPECTED_COLLECTION_AFTER_EACH_IN:Int = 43
Const LANGUAGE_MSG_PARSER_MULTIPLE_FOR_BINDINGS_REQUIRE_EACH_IN:Int = 44
Const LANGUAGE_MSG_PARSER_EXPECTED_INITIAL_VALUE_BEFORE_RANGE_CLAUSE:Int = 45
Const LANGUAGE_MSG_PARSER_EXPECTED_RANGE_LIMIT_AFTER_CLAUSE:Int = 46
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_STEP:Int = 47
Const LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_LOOP_VARIABLE_BETWEEN_COMMAS:Int = 48
Const LANGUAGE_MSG_PARSER_CASE_CANNOT_FOLLOW_DEFAULT:Int = 49
Const LANGUAGE_MSG_PARSER_SELECT_ALLOWS_SINGLE_DEFAULT:Int = 50
Const LANGUAGE_MSG_PARSER_EXPECTED_SELECT_CLAUSE_OR_END:Int = 51
Const LANGUAGE_MSG_PARSER_EXPECTED_END_SELECT:Int = 52
Const LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_SELECT_CLAUSE:Int = 53
Const LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_SELECT_END:Int = 54
Const LANGUAGE_MSG_PARSER_TRY_REJECTS_HEADER_EXPRESSION:Int = 55
Const LANGUAGE_MSG_PARSER_CATCH_CANNOT_FOLLOW_FINALLY:Int = 56
Const LANGUAGE_MSG_PARSER_TRY_ALLOWS_SINGLE_FINALLY:Int = 57
Const LANGUAGE_MSG_PARSER_TRY_REQUIRES_CATCH_OR_FINALLY:Int = 58
Const LANGUAGE_MSG_PARSER_EXPECTED_END_TRY:Int = 59
Const LANGUAGE_MSG_PARSER_EXPECTED_CAUGHT_VALUE_TYPE:Int = 60
Const LANGUAGE_MSG_PARSER_EXPECTED_CAUGHT_VALUE_NAME:Int = 61
Const LANGUAGE_MSG_PARSER_FINALLY_REJECTS_HEADER_EXPRESSION:Int = 62
Const LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_RESOURCE_AFTER_USING:Int = 63
Const LANGUAGE_MSG_PARSER_USING_REQUIRES_LOCAL_RESOURCES_BEFORE_DO:Int = 64
Const LANGUAGE_MSG_PARSER_USING_REQUIRES_LOCAL_RESOURCE:Int = 65
Const LANGUAGE_MSG_PARSER_EXPECTED_DO_AFTER_USING_RESOURCES:Int = 66
Const LANGUAGE_MSG_PARSER_EXPECTED_END_USING:Int = 67
Const LANGUAGE_MSG_BINDING_YIELDING_ROUTINE_REQUIRES_ITERATOR_RETURN:Int = 68
Const LANGUAGE_MSG_BINDING_ARRAY_DIMENSION_REQUIRES_INTEGRAL_TYPE:Int = 69
Const LANGUAGE_MSG_BINDING_READONLY_FIELD_ASSIGNMENT_REQUIRES_CONSTRUCTOR:Int = 70
Const LANGUAGE_MSG_BINDING_YIELDING_ROUTINE_REQUIRES_BARE_RETURN:Int = 71
Const LANGUAGE_MSG_BINDING_VOID_ROUTINE_RETURN_REJECTS_EXPRESSION:Int = 72
Const LANGUAGE_MSG_BINDING_MODULE_ENTRY_RETURN_REQUIRES_VALUE:Int = 73
Const LANGUAGE_MSG_BINDING_YIELD_REQUIRES_ROUTINE:Int = 74
Const LANGUAGE_MSG_BINDING_RELEASE_REQUIRES_WRITABLE_INTEGER:Int = 75
Const LANGUAGE_MSG_BINDING_RELEASE_REQUIRES_INTEGER:Int = 76
Const LANGUAGE_MSG_BINDING_SELECT_ALLOWS_SINGLE_ACTIVE_DEFAULT:Int = 77
Const LANGUAGE_MSG_BINDING_ACTIVE_CASE_CANNOT_FOLLOW_DEFAULT:Int = 78
Const LANGUAGE_MSG_BINDING_CANNOT_INFER_EMPTY_ARRAY_LOCAL:Int = 79
Const LANGUAGE_MSG_BINDING_CANNOT_INFER_NULL_LOCAL:Int = 80
Const LANGUAGE_MSG_BINDING_INFERRED_LOCAL_INITIALIZER_HAS_NO_VALUE:Int = 81
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_REQUIRES_CALLABLE_TARGET:Int = 82
Const LANGUAGE_MSG_BINDING_QUALIFIED_SUPER_REQUIRES_INTERFACE:Int = 83
Const LANGUAGE_MSG_BINDING_INTERFACE_NOT_INHERITED_BY_CURRENT_TYPE:Int = 84
Const LANGUAGE_MSG_BINDING_BOUND_METHOD_RECEIVER_REQUIRES_REFERENCE_TYPE:Int = 85
Const LANGUAGE_MSG_BINDING_NAME_NOT_RESOLVED_AS_VALUE:Int = 86
Const LANGUAGE_MSG_BINDING_NAMED_CAST_REQUIRES_ONE_EXPRESSION:Int = 87
Const LANGUAGE_MSG_BINDING_EXPLICIT_CONVERSION_NOT_AVAILABLE:Int = 88
Const LANGUAGE_MSG_BINDING_QUALIFIED_SUPER_REQUIRES_DEFAULT_INTERFACE_METHOD:Int = 89
Const LANGUAGE_MSG_BINDING_CANNOT_INSTANTIATE_ABSTRACT_TYPE:Int = 90
Const LANGUAGE_MSG_BINDING_RANGE_SLICING_REQUIRES_ONE_DIMENSIONAL_ARRAY:Int = 91
Const LANGUAGE_MSG_BINDING_RANGE_SLICING_REJECTS_STATIC_ARRAY:Int = 92
Const LANGUAGE_MSG_BINDING_TYPE_HAS_NO_APPLICABLE_INDEXING_OPERATOR:Int = 93
Const LANGUAGE_MSG_BINDING_INDEX_EXPRESSION_REQUIRES_UINT_CONVERSION:Int = 94
Const LANGUAGE_MSG_BINDING_SLICE_BOUND_REQUIRES_INT_CONVERSION:Int = 95
Const LANGUAGE_MSG_BINDING_TYPE_DOES_NOT_SUPPORT_SLICING:Int = 96
Const LANGUAGE_MSG_BINDING_RANGE_REQUIRES_BRL_RANGE:Int = 97
Const LANGUAGE_MSG_BINDING_RANGE_ENDPOINT_REQUIRES_INT_CONVERSION:Int = 98
Const LANGUAGE_MSG_BINDING_BOUND_METHOD_REFERENCE_AMBIGUOUS_FOR_TARGET:Int = 99
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_REQUIRES_SUPER_STRICT:Int = 100
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_COUNT_MISMATCH:Int = 101
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_TYPE_MISMATCH:Int = 102
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_REQUIRES_VAR_MODE:Int = 103
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETERS_REJECT_DEFAULTS:Int = 104
Const LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_RETURN_TYPE_MISMATCH:Int = 105
Const LANGUAGE_MSG_BINDING_THIN_FUNCTION_LITERAL_CANNOT_CAPTURE:Int = 106
Const LANGUAGE_MSG_BINDING_MANAGED_CLOSURE_CANNOT_CAPTURE:Int = 107
Const LANGUAGE_MSG_BINDING_MEMBER_NOT_RESOLVED:Int = 108
Const LANGUAGE_MSG_BINDING_GENERIC_ROUTINE_REFERENCE_HAS_NO_SPECIALIZATION:Int = 109
Const LANGUAGE_MSG_BINDING_GENERIC_ROUTINE_REFERENCE_IS_AMBIGUOUS:Int = 110
Const LANGUAGE_MSG_BINDING_DEFAULT_CONSTRUCTOR_INACCESSIBLE:Int = 111
Const LANGUAGE_MSG_BINDING_IMPLICIT_CONVERSION_NOT_AVAILABLE:Int = 112
Const LANGUAGE_MSG_BINDING_CANNOT_CALL_ABSTRACT_FUNCTION:Int = 113
Const LANGUAGE_MSG_BINDING_ROUTINE_USED_AS_VALUE:Int = 114
Const LANGUAGE_MSG_BINDING_SYMBOL_INACCESSIBLE_FROM_SCOPE:Int = 115
Const LANGUAGE_MSG_BINDING_GENERIC_TYPE_QUALIFIER_NOT_RESOLVED:Int = 116
Const LANGUAGE_MSG_BINDING_GENERIC_TYPE_ARGUMENT_COUNT_MISMATCH:Int = 117
Const LANGUAGE_MSG_BINDING_ASC_REQUIRES_STRING_CONVERSION:Int = 118
Const LANGUAGE_MSG_BINDING_CHR_REQUIRES_INT_CONVERSION:Int = 119
Const LANGUAGE_MSG_BINDING_STACK_ALLOC_REQUIRES_SIZE_T_CONVERSION:Int = 120
Const LANGUAGE_MSG_BINDING_VAR_PTR_REQUIRES_WRITABLE_STORAGE:Int = 121
Const LANGUAGE_MSG_BINDING_STANDARD_RANGE_MISSING_BOUND_RESOLUTION:Int = 122
Const LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_REQUIRES_NEW_SYNTAX:Int = 123
Const LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_REQUIRES_NEW_METHOD:Int = 124
Const LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_MUST_BE_FIRST:Int = 125
Const LANGUAGE_MSG_BINDING_CONSTRUCTOR_CANNOT_DELEGATE_TO_ITSELF:Int = 126
Const LANGUAGE_MSG_BINDING_ITERATION_REQUIRES_SUPPORTED_SOURCE:Int = 127
Const LANGUAGE_MSG_BINDING_ITERATOR_FACTORY_RETURN_TYPE_UNUSABLE:Int = 128
Const LANGUAGE_MSG_BINDING_ITERATOR_MISSING_REQUIRED_METHODS:Int = 129
Const LANGUAGE_MSG_BINDING_ITERATOR_METHOD_RETURNS_INVALID:Int = 130
Const LANGUAGE_MSG_BINDING_EACH_IN_DECONSTRUCTION_REQUIRES_TWO_BINDINGS:Int = 131
Const LANGUAGE_MSG_BINDING_EACH_IN_ELEMENT_REQUIRES_DECONSTRUCT2:Int = 132
Const LANGUAGE_MSG_BINDING_DECONSTRUCT2_REQUIRES_METHOD_CONTRACT:Int = 133
Const LANGUAGE_MSG_BINDING_EACH_IN_DECONSTRUCTION_BINDING_TYPE_MISMATCH:Int = 134
Const LANGUAGE_MSG_BINDING_EACH_IN_ELEMENT_CONVERSION_NOT_AVAILABLE:Int = 135
Const LANGUAGE_MSG_DATA_DUPLICATE_LABEL:Int = 136
Const LANGUAGE_MSG_DATA_ITEM_REQUIRES_CONSTANT_NUMERIC_OR_STRING:Int = 137
Const LANGUAGE_MSG_DATA_ITEM_MISSING_BETWEEN_SEPARATORS:Int = 138
Const LANGUAGE_MSG_DATA_RESTORE_REQUIRES_LABEL_NAME:Int = 139
Const LANGUAGE_MSG_DATA_LABEL_NOT_FOUND:Int = 140
Const LANGUAGE_MSG_DATA_READ_TARGET_REQUIRES_WRITABLE_STORAGE:Int = 141
Const LANGUAGE_MSG_DATA_READ_TARGET_TYPE_UNSUPPORTED:Int = 142
Const LANGUAGE_MSG_DATA_READ_TARGET_MISSING_BETWEEN_SEPARATORS:Int = 143
Const LANGUAGE_MSG_CONSTANT_DEFINITION_CYCLE:Int = 144
Const LANGUAGE_MSG_CONSTANT_REQUIRES_INITIALIZER:Int = 145
Const LANGUAGE_MSG_CONSTANT_IMPORTED_ENUM_VALUE_UNUSABLE:Int = 146
Const LANGUAGE_MSG_CONSTANT_ENUM_VALUE_OUT_OF_RANGE:Int = 147
Const LANGUAGE_MSG_CONSTANT_ENUM_VALUE_REQUIRES_INTEGRAL_EXPRESSION:Int = 148
Const LANGUAGE_MSG_CONSTANT_VALUE_OUT_OF_RANGE:Int = 149
Const LANGUAGE_MSG_COMPILE_TIME_ENUM_CONSTANT_VALUE_INVALID:Int = 150
Const LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_ELEMENT_TYPE_UNSUPPORTED:Int = 151
Const LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_LENGTH_REQUIRES_INTEGRAL_CONSTANT:Int = 152
Const LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_LENGTH_OUT_OF_RANGE:Int = 153
Const LANGUAGE_MSG_COMPILE_TIME_PARAMETER_DEFAULT_REQUIRES_CONSTANT:Int = 154
Const LANGUAGE_MSG_COMPILE_TIME_PARAMETER_CONSTANT_DEFAULT_INCOMPATIBLE:Int = 155
Const LANGUAGE_MSG_COMPILE_TIME_SEMANTIC_PARAMETER_MISSING:Int = 156
Const LANGUAGE_MSG_COMPILE_TIME_SEMANTIC_PARAMETER_IDENTITY_MISMATCH:Int = 157
Const LANGUAGE_MSG_CONTROL_FLOW_IMPLICIT_DEFAULT_RETURN_REACHABLE:Int = 158
Const LANGUAGE_MSG_CONTROL_FLOW_LOOP_CONTROL_REQUIRES_LOOP:Int = 159
Const LANGUAGE_MSG_CONTROL_FLOW_LOOP_CONTROL_REQUIRES_LABEL_NAME:Int = 160
Const LANGUAGE_MSG_CONTROL_FLOW_LOOP_LABEL_NOT_FOUND:Int = 161
Const LANGUAGE_MSG_CONTROL_FLOW_UNREACHABLE_STATEMENT:Int = 162
Const LANGUAGE_MSG_INHERITANCE_PUBLIC_CONTRACT_EXPOSES_HIDDEN_TYPE:Int = 163
Const LANGUAGE_MSG_INHERITANCE_OVERRIDE_METHOD_NOT_FOUND:Int = 164
Const LANGUAGE_MSG_INHERITANCE_OVERRIDE_REDUCES_VISIBILITY:Int = 165
Const LANGUAGE_MSG_INHERITANCE_DEFAULT_REQUIRES_INTERFACE_INSTANCE_METHOD:Int = 166
Const LANGUAGE_MSG_INHERITANCE_INTERFACE_DEFAULT_CANNOT_BE_ABSTRACT:Int = 167
Const LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_PARAMETER_UNDECLARED:Int = 168
Const LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_DUPLICATE_CLAUSE:Int = 169
Const LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_BOUND_INVALID:Int = 170
Const LANGUAGE_MSG_INHERITANCE_STRUCT_CANNOT_INHERIT:Int = 171
Const LANGUAGE_MSG_INHERITANCE_TYPE_ALLOWS_SINGLE_BASE:Int = 172
Const LANGUAGE_MSG_INHERITANCE_INTERFACE_BASE_REQUIRES_INTERFACE:Int = 173
Const LANGUAGE_MSG_INHERITANCE_EXTERNAL_MANAGED_INTERFACE_MISMATCH:Int = 174
Const LANGUAGE_MSG_INHERITANCE_TYPE_BASE_REQUIRES_REFERENCE_TYPE:Int = 175
Const LANGUAGE_MSG_INHERITANCE_FINAL_TYPE_CANNOT_BE_EXTENDED:Int = 176
Const LANGUAGE_MSG_INHERITANCE_INTERFACE_CANNOT_USE_IMPLEMENTS:Int = 177
Const LANGUAGE_MSG_INHERITANCE_IMPLEMENTS_TARGET_NOT_INTERFACE:Int = 178
Const LANGUAGE_MSG_INHERITANCE_INTERFACE_SELECTOR_RETURN_TYPES_INCOMPATIBLE:Int = 179
Const LANGUAGE_MSG_INHERITANCE_UNRELATED_INTERFACE_DEFAULTS:Int = 180
Const LANGUAGE_MSG_INHERITANCE_INTERFACE_LISTED_MORE_THAN_ONCE:Int = 181
Const LANGUAGE_MSG_INHERITANCE_CYCLE:Int = 182
Const LANGUAGE_MSG_INHERITANCE_TYPE_ARGUMENT_CONSTRAINT_UNSATISFIED:Int = 183
Const LANGUAGE_MSG_TYPE_RESOLUTION_SYMBOL_REQUIRES_EXPLICIT_TYPE:Int = 184
Const LANGUAGE_MSG_TYPE_RESOLUTION_CALLING_CONVENTION_UNRECOGNIZED:Int = 185
Const LANGUAGE_MSG_TYPE_RESOLUTION_CALLABLE_PARAMETER_REQUIRES_EXPLICIT_TYPE:Int = 186
Const LANGUAGE_MSG_TYPE_RESOLUTION_ROUTINE_CONSTRAINT_PARAMETER_UNDECLARED:Int = 187
Const LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_REQUIRES_SUPERSTRICT:Int = 188
Const LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_REQUIRES_EXPLICIT_SIGNATURE:Int = 189
Const LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_PARAMETER_REQUIRES_NAME_AND_TYPE:Int = 190
Const LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_SIGNATURE_REJECTS_DEFAULT:Int = 191
Const LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_SIGNATURE_REJECTS_NATIVE_CALLING_CONVENTION:Int = 192
Const LANGUAGE_MSG_TYPE_RESOLUTION_AMBIGUOUS_TYPE_NAME:Int = 193
Const LANGUAGE_MSG_TYPE_RESOLUTION_TYPE_PARAMETER_REJECTS_TYPE_ARGUMENTS:Int = 194
Const LANGUAGE_MSG_TYPE_RESOLUTION_TYPE_NOT_RESOLVED:Int = 195
Const LANGUAGE_MSG_SNAPSHOT_DEPENDENCIES_UNRESOLVED:Int = 196
Const LANGUAGE_MSG_SNAPSHOT_IMPLICIT_RUNTIME_INTERFACE_UNAVAILABLE:Int = 197
Const LANGUAGE_MSG_SNAPSHOT_IMPLICIT_APPLICATION_INTERFACE_UNAVAILABLE:Int = 198
Const LANGUAGE_MSG_SNAPSHOT_CORE_INTERFACE_MISSING:Int = 199
Const LANGUAGE_MSG_SNAPSHOT_INCLUDE_CYCLE:Int = 200
Const LANGUAGE_MSG_SNAPSHOT_INCLUDED_SOURCE_NOT_FOUND:Int = 201
Const LANGUAGE_MSG_SNAPSHOT_COMPILER_INTERFACE_UNAVAILABLE:Int = 202
Const LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_FORMAT_UNSUPPORTED:Int = 203
Const LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_ARTIFACT_UNAVAILABLE:Int = 204
Const LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_ARTIFACT_INVALID:Int = 205
Const LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_IDENTITY_MISMATCH:Int = 206
Const LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_LANGUAGE_REVISION_MISMATCH:Int = 207
Const LANGUAGE_MSG_LEXER_NUMERIC_EXPONENT_REQUIRES_DIGIT:Int = 208
Const LANGUAGE_MSG_LEXER_UNTERMINATED_MULTILINE_STRING:Int = 209
Const LANGUAGE_MSG_LEXER_UNTERMINATED_STRING:Int = 210
Const LANGUAGE_MSG_LEXER_BAD_STRING_ESCAPE:Int = 211
Const LANGUAGE_MSG_LEXER_UNTERMINATED_REM_COMMENT:Int = 212
Const LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_REGION_END:Int = 213
Const LANGUAGE_MSG_PARSER_INFERRED_LOCAL_SYNTAX_REQUIRED:Int = 214
Const LANGUAGE_MSG_PARSER_EXPECTED_ROUTINE_NAME:Int = 215
Const LANGUAGE_MSG_PARSER_INTERFACE_METHOD_REJECTS_BODY:Int = 216
Const LANGUAGE_MSG_PARSER_EXPECTED_TYPE_NAME:Int = 217
Const LANGUAGE_MSG_PARSER_EXPECTED_BLOCK_END_BEFORE_EOF:Int = 218
Const LANGUAGE_MSG_PARSER_MISMATCHED_BLOCK_END:Int = 219
Const LANGUAGE_MSG_PARSER_EXPECTED_IMPORT_TARGET:Int = 220
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_IMPORT_PATH:Int = 221
Const LANGUAGE_MSG_PARSER_EXPECTED_INCLUDE_PATH:Int = 222
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_INCLUDE_PATH:Int = 223
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_YIELD_FROM:Int = 224
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_YIELD:Int = 225
Const LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_THROW:Int = 226
Const LANGUAGE_MSG_PARSER_EXPECTED_INTEGER_VARIABLE_AFTER_RELEASE:Int = 227
Const LANGUAGE_MSG_PARSER_DEFDATA_REQUIRES_VALUE:Int = 228
Const LANGUAGE_MSG_PARSER_RESTOREDATA_REQUIRES_LABEL:Int = 229
Const LANGUAGE_MSG_PARSER_EXPECTED_CONDITION_AFTER_ASSERT:Int = 230
Const LANGUAGE_MSG_PARSER_EXPECTED_ASSERT_MESSAGE:Int = 231
Const LANGUAGE_MSG_PARSER_INFERENCE_REQUIRES_LOCAL:Int = 232
Const LANGUAGE_MSG_PARSER_INFERRED_LOCAL_REQUIRES_SINGLE_DECLARATOR:Int = 233
Const LANGUAGE_MSG_PARSER_EXPECTED_VARIABLE_NAME:Int = 234
Const LANGUAGE_MSG_PARSER_INFERRED_LOCAL_REQUIRES_INITIALIZER:Int = 235
Const LANGUAGE_MSG_PARSER_STATIC_ARRAY_REQUIRES_BRACKETED_LENGTH:Int = 236
Const LANGUAGE_MSG_PARSER_STATIC_ARRAY_REQUIRES_LENGTH_EXPRESSION:Int = 237
Const LANGUAGE_MSG_PARSER_EXPECTED_CASE_VALUE_AFTER_COMMA:Int = 238
Const LANGUAGE_MSG_PARSER_EXPECTED_CASE_VALUE:Int = 239
Const LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_IN_FUNCTION_LITERAL:Int = 240
Const LANGUAGE_MSG_PARSER_EXPECTED_CLOSE_PARENTHESIS_IN_FUNCTION_LITERAL:Int = 241
Const LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_FUNCTION_LITERAL_PARAMETERS:Int = 242
Const LANGUAGE_MSG_SIGNATURE_EXPECTED_GENERIC_PARAMETER_END:Int = 243
Const LANGUAGE_MSG_SIGNATURE_EXPECTED_ROUTINE_PARENTHESIS:Int = 244
Const LANGUAGE_MSG_SIGNATURE_EXPECTED_ROUTINE_CLOSE_PARENTHESIS:Int = 245
Const LANGUAGE_MSG_SIGNATURE_EXPECTED_PARAMETER_NAME:Int = 246
Const LANGUAGE_MSG_SIGNATURE_STATIC_ARRAY_PARAMETER_REQUIRES_BRACKETED_LENGTH:Int = 247
Const LANGUAGE_MSG_SIGNATURE_STATIC_ARRAY_PARAMETER_REQUIRES_LENGTH_EXPRESSION:Int = 248
Const LANGUAGE_MSG_SIGNATURE_EXPECTED_CALLABLE_CLOSE_PARENTHESIS:Int = 249
Const LANGUAGE_MSG_DECLARATION_DUPLICATE:Int = 250
Const LANGUAGE_MSG_DECLARATION_NOMANGLE_REQUIRES_FUNCTION:Int = 251
Const LANGUAGE_MSG_DECLARATION_NOMANGLE_OVERLOAD_CONFLICT:Int = 252
Const LANGUAGE_MSG_METADATA_EXPECTED_KEY:Int = 253
Const LANGUAGE_MSG_METADATA_EXPECTED_LITERAL_VALUE:Int = 254
Const LANGUAGE_MSG_METADATA_DUPLICATE_KEY:Int = 255
Const LANGUAGE_MSG_METADATA_EXPECTED_CLOSE_BRACE:Int = 256
Const LANGUAGE_MSG_INTERFACE_UNTERMINATED_RECORD:Int = 257
Const LANGUAGE_MSG_INTERFACE_GENERIC_TEMPLATE_REQUIRES_DECLARATION:Int = 258
Const LANGUAGE_MSG_INTERFACE_GENERIC_TEMPLATE_REFERENCE_INVALID:Int = 259
Const LANGUAGE_MSG_BINDING_DYNAMIC_NEW_INSTANCE_DEPRECATED:Int = 260
Const LANGUAGE_MSG_BINDING_CALL_AMBIGUOUS:Int = 261
Const LANGUAGE_MSG_BINDING_NO_APPLICABLE_OVERLOAD:Int = 262
Const LANGUAGE_MSG_BINDING_VARIABLE_ASSIGNED_TO_ITSELF:Int = 263

Type TLanguageMessages
	Function ParserExpressionNestingTooDeep:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPRESSION_NESTING_TOO_DEEP, "Expression nesting is too deep to parse safely.")
	End Function
	Function ParserExpectedExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION, "Expected an expression.")
	End Function
	Function ParserUnexpectedTokenInExpression:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_IN_EXPRESSION, "Unexpected token '{token}' in expression.", [TMessageArg.Create("token", token)])
	End Function
	Function ParserExpectedCloseParenthesis:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CLOSE_PARENTHESIS, "Expected ')' to close expression.")
	End Function
	Function ParserExpectedQualifiedSuperInterface:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_QUALIFIED_SUPER_INTERFACE, "Expected an Interface type in qualified Super expression.")
	End Function
	Function ParserExpectedExpressionFoundToken:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_FOUND_TOKEN, "Expected an expression but found '{token}'.", [TMessageArg.Create("token", token)])
	End Function
	Function ParserExpectedParenthesisAfterArguments:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_ARGUMENTS, "Expected ')' after argument list.")
	End Function
	Function ParserExpectedBracketAfterIndexes:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_INDEXES, "Expected ']' after index list.")
	End Function
	Function ConstantDivisionByZero:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_DIVISION_BY_ZERO, "Division by zero in constant expression.")
	End Function
	Function TypeExpectedTypeArguments:TLocalisedMessage(typeName:String, expected:Long, supplied:Long)
		Return TLocalisedMessage.CreatePlural("language", LANGUAGE_MSG_TYPE_EXPECTED_TYPE_ARGUMENTS, "expected", ["", "Type '{typeName}' expects one type argument, but {supplied} were supplied.", "", "", "", "Type '{typeName}' expects {expected} type arguments, but {supplied} were supplied."], [TMessageArg.Create("typeName", typeName), TMessageArg.CreateInt("expected", expected), TMessageArg.CreateInt("supplied", supplied)])
	End Function
	Function ConditionalExpectedExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONDITIONAL_EXPECTED_EXPRESSION, "Expected a conditional-compilation expression.")
	End Function
	Function ConditionalUnexpectedToken:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONDITIONAL_UNEXPECTED_TOKEN, "Unexpected token '{token}' in conditional-compilation expression.", [TMessageArg.Create("token", token)])
	End Function
	Function ConditionalExpectedCloseParenthesis:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONDITIONAL_EXPECTED_CLOSE_PARENTHESIS, "Expected ')' in conditional-compilation expression.")
	End Function
	Function ConditionalExpectedOperand:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONDITIONAL_EXPECTED_OPERAND, "Expected a target symbol, 'Not', or '('.")
	End Function
	Function ParserParenthesizeCalculatedFromEndEndpoint:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_PARENTHESIZE_CALCULATED_FROM_END_ENDPOINT, "Parenthesize a calculated from-end Range endpoint as '^(expression)'.")
	End Function
	Function ParserFromEndEndpointRequiresRange:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_FROM_END_ENDPOINT_REQUIRES_RANGE, "A from-end endpoint requires a Range expression.")
	End Function
	Function ParserExpectedBracketAfterSlice:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_SLICE, "Expected ']' after slice.")
	End Function
	Function ParserPostfixTypeRequiresNumericLiteral:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_POSTFIX_TYPE_REQUIRES_NUMERIC_LITERAL, "A postfix ':Type' is valid only on a numeric literal; use Type(expression) for an explicit conversion.")
	End Function
	Function ParserExpectedTypeAfterNew:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_TYPE_AFTER_NEW, "Expected a type after 'New'.")
	End Function
	Function ParserExpectedParenthesisAfterConstructorArguments:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_CONSTRUCTOR_ARGUMENTS, "Expected ')' after constructor arguments.")
	End Function
	Function ParserExpectedBracketAfterArrayLiteral:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_BRACKET_AFTER_ARRAY_LITERAL, "Expected ']' after array literal.")
	End Function
	Function ParserExpectedParenthesisAfterCast:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_AFTER_CAST, "Expected ')' after cast expression.")
	End Function
	Function ParserUnexpectedTokenAfterSourceMode:TLocalisedMessage(token:String, mode:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_SOURCE_MODE, "Unexpected token '{token}' after '{mode}'.", [TMessageArg.Create("token", token), TMessageArg.Create("mode", mode)])
	End Function
	Function ParserVisibilityOnlyInsideType:TLocalisedMessage(visibility:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_VISIBILITY_ONLY_INSIDE_TYPE, "'{visibility}' visibility is only valid inside a type.", [TMessageArg.Create("visibility", visibility)])
	End Function
	Function ParserVisibilityNotValidForInterface:TLocalisedMessage(visibility:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_VISIBILITY_NOT_VALID_FOR_INTERFACE, "'{visibility}' visibility cannot be used with interfaces.", [TMessageArg.Create("visibility", visibility)])
	End Function
	Function ParserExpectedEnumName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_ENUM_NAME, "Expected an enum name.")
	End Function
	Function ParserExpectedEnumUnderlyingType:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_ENUM_UNDERLYING_TYPE, "Expected an enum underlying type after ':'.")
	End Function
	Function ParserExpectedEndEnum:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_ENUM, "Expected 'End Enum' before end of file.")
	End Function
	Function ParserExpectedEnumValueName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_ENUM_VALUE_NAME, "Expected an enum value name.")
	End Function
	Function ParserExpectedConstantExpressionAfterEquals:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CONSTANT_EXPRESSION_AFTER_EQUALS, "Expected a constant expression after '='.")
	End Function
	Function ParserExpectedLoopLabelName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_LOOP_LABEL_NAME, "Expected a loop-label name after '#'.")
	End Function
	Function ParserUnexpectedTokenAfterLoopLabel:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_LOOP_LABEL, "Unexpected token '{token}' after loop label.", [TMessageArg.Create("token", token)])
	End Function
	Function ParserExpectedEndIf:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_IF, "Expected 'End If' or 'EndIf'.")
	End Function
	Function ParserExpectedEndWhile:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_WHILE, "Expected 'Wend' or 'End While'.")
	End Function
	Function ParserExpectedRepeatTerminator:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_REPEAT_TERMINATOR, "Expected 'Until' or 'Forever'.")
	End Function
	Function ParserExpectedNext:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_NEXT, "Expected 'Next'.")
	End Function
	Function ParserExpectedForLoopHeader:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_FOR_LOOP_HEADER, "Expected a For-loop header.")
	End Function
	Function ParserExpectedEqualsInForLoopHeader:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EQUALS_IN_FOR_LOOP_HEADER, "Expected '=' in For-loop header.")
	End Function
	Function ParserExpectedLocalLoopVariableBeforeEquals:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_LOOP_VARIABLE_BEFORE_EQUALS, "Expected a local loop variable before '='.")
	End Function
	Function ParserExpectedLoopTargetBeforeEquals:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_LOOP_TARGET_BEFORE_EQUALS, "Expected a loop target before '='.")
	End Function
	Function ParserExpectedForLoopClause:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_FOR_LOOP_CLAUSE, "Expected 'EachIn', 'To', or 'Until' in For-loop header.")
	End Function
	Function ParserEachInMustFollowEquals:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EACH_IN_MUST_FOLLOW_EQUALS, "'EachIn' must immediately follow '='.")
	End Function
	Function ParserExpectedCollectionAfterEachIn:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_COLLECTION_AFTER_EACH_IN, "Expected a collection after 'EachIn'.")
	End Function
	Function ParserMultipleForBindingsRequireEachIn:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_MULTIPLE_FOR_BINDINGS_REQUIRE_EACH_IN, "Multiple For-loop bindings are valid only with 'EachIn'.")
	End Function
	Function ParserExpectedInitialValueBeforeRangeClause:TLocalisedMessage(clause:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_INITIAL_VALUE_BEFORE_RANGE_CLAUSE, "Expected an initial value before '{clause}'.", [TMessageArg.Create("clause", clause)])
	End Function
	Function ParserExpectedRangeLimitAfterClause:TLocalisedMessage(clause:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_RANGE_LIMIT_AFTER_CLAUSE, "Expected a range limit after '{clause}'.", [TMessageArg.Create("clause", clause)])
	End Function
	Function ParserExpectedExpressionAfterStep:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_STEP, "Expected an expression after 'Step'.")
	End Function
	Function ParserExpectedLocalLoopVariableBetweenCommas:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_LOOP_VARIABLE_BETWEEN_COMMAS, "Expected a local loop variable between commas.")
	End Function
	Function ParserCaseCannotFollowDefault:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_CASE_CANNOT_FOLLOW_DEFAULT, "A Case clause cannot follow Default.")
	End Function
	Function ParserSelectAllowsSingleDefault:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_SELECT_ALLOWS_SINGLE_DEFAULT, "A Select statement can contain only one Default clause.")
	End Function
	Function ParserExpectedSelectClauseOrEnd:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_SELECT_CLAUSE_OR_END, "Expected 'Case', 'Default', or 'End Select'.")
	End Function
	Function ParserExpectedEndSelect:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_SELECT, "Expected 'End Select' or 'EndSelect'.")
	End Function
	Function ParserExpectedConditionalSelectClause:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_SELECT_CLAUSE, "Expected 'Case', 'Default', or a conditional directive inside Select.")
	End Function
	Function ParserExpectedConditionalSelectEnd:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_SELECT_END, "Expected '?' to end conditional Select clauses.")
	End Function
	Function ParserTryRejectsHeaderExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_TRY_REJECTS_HEADER_EXPRESSION, "Try does not accept a header expression.")
	End Function
	Function ParserCatchCannotFollowFinally:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_CATCH_CANNOT_FOLLOW_FINALLY, "A Catch clause cannot follow Finally.")
	End Function
	Function ParserTryAllowsSingleFinally:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_TRY_ALLOWS_SINGLE_FINALLY, "A Try statement can contain only one Finally clause.")
	End Function
	Function ParserTryRequiresCatchOrFinally:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_TRY_REQUIRES_CATCH_OR_FINALLY, "A Try statement requires Catch or Finally.")
	End Function
	Function ParserExpectedEndTry:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_TRY, "Expected 'End Try' or 'EndTry'.")
	End Function
	Function ParserExpectedCaughtValueType:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CAUGHT_VALUE_TYPE, "Expected a caught value type.")
	End Function
	Function ParserExpectedCaughtValueName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CAUGHT_VALUE_NAME, "Expected a caught value name.")
	End Function
	Function ParserFinallyRejectsHeaderExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_FINALLY_REJECTS_HEADER_EXPRESSION, "Finally does not accept a header expression.")
	End Function
	Function ParserExpectedLocalResourceAfterUsing:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_LOCAL_RESOURCE_AFTER_USING, "Expected a Local resource declaration after Using.")
	End Function
	Function ParserUsingRequiresLocalResourcesBeforeDo:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_USING_REQUIRES_LOCAL_RESOURCES_BEFORE_DO, "Using requires Local resource declarations before Do.")
	End Function
	Function ParserUsingRequiresLocalResource:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_USING_REQUIRES_LOCAL_RESOURCE, "Using requires at least one Local resource declaration.")
	End Function
	Function ParserExpectedDoAfterUsingResources:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_DO_AFTER_USING_RESOURCES, "Expected 'Do' after Using resources.")
	End Function
	Function ParserExpectedEndUsing:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_END_USING, "Expected 'End Using' or 'EndUsing'.")
	End Function
	Function BindingYieldingRoutineRequiresIteratorReturn:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_YIELDING_ROUTINE_REQUIRES_ITERATOR_RETURN, "A routine containing Yield must return IIterator<T>, ICloseableIterator<T>, or a compatible iterator Interface.")
	End Function
	Function BindingArrayDimensionRequiresIntegralType:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ARRAY_DIMENSION_REQUIRES_INTEGRAL_TYPE, "Type '{typeName}' is not valid for an array dimension; an integral type is required.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingReadonlyFieldAssignmentRequiresConstructor:TLocalisedMessage(fieldName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_READONLY_FIELD_ASSIGNMENT_REQUIRES_CONSTRUCTOR, "ReadOnly field '{fieldName}' can only be assigned in a constructor.", [TMessageArg.Create("fieldName", fieldName)])
	End Function
	Function BindingYieldingRoutineRequiresBareReturn:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_YIELDING_ROUTINE_REQUIRES_BARE_RETURN, "A yielding routine can use only bare Return to complete the iterator.")
	End Function
	Function BindingVoidRoutineReturnRejectsExpression:TLocalisedMessage(routineKind:String, routineName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_VOID_ROUTINE_RETURN_REJECTS_EXPRESSION, "{routineKind} '{routineName}' does not return a value, so Return cannot include an expression.", [TMessageArg.Create("routineKind", routineKind), TMessageArg.Create("routineName", routineName)])
	End Function
	Function BindingModuleEntryReturnRequiresValue:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_MODULE_ENTRY_RETURN_REQUIRES_VALUE, "The module entry returns Int, so Return requires a value in SuperStrict code.")
	End Function
	Function BindingYieldRequiresRoutine:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_YIELD_REQUIRES_ROUTINE, "Yield is valid only inside a Function or Method.")
	End Function
	Function BindingReleaseRequiresWritableInteger:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RELEASE_REQUIRES_WRITABLE_INTEGER, "Release requires a writable integer variable.")
	End Function
	Function BindingReleaseRequiresInteger:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RELEASE_REQUIRES_INTEGER, "Release requires an integer variable, not '{typeName}'.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingSelectAllowsSingleActiveDefault:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_SELECT_ALLOWS_SINGLE_ACTIVE_DEFAULT, "A Select statement can contain only one active Default clause.")
	End Function
	Function BindingActiveCaseCannotFollowDefault:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ACTIVE_CASE_CANNOT_FOLLOW_DEFAULT, "An active Case clause cannot follow Default.")
	End Function
	Function BindingCannotInferEmptyArrayLocal:TLocalisedMessage(localName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CANNOT_INFER_EMPTY_ARRAY_LOCAL, "The type of local '{localName}' cannot be inferred from an empty array literal; write an explicit array type.", [TMessageArg.Create("localName", localName)])
	End Function
	Function BindingCannotInferNullLocal:TLocalisedMessage(localName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CANNOT_INFER_NULL_LOCAL, "The type of local '{localName}' cannot be inferred from Null; write an explicit reference type.", [TMessageArg.Create("localName", localName)])
	End Function
	Function BindingInferredLocalInitializerHasNoValue:TLocalisedMessage(localName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_INFERRED_LOCAL_INITIALIZER_HAS_NO_VALUE, "The initializer for inferred local '{localName}' does not produce a value.", [TMessageArg.Create("localName", localName)])
	End Function
	Function BindingFunctionLiteralRequiresCallableTarget:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_REQUIRES_CALLABLE_TARGET, "A Function literal requires an explicit callable target type.")
	End Function
	Function BindingQualifiedSuperRequiresInterface:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_QUALIFIED_SUPER_REQUIRES_INTERFACE, "Qualified Super requires an Interface type.")
	End Function
	Function BindingInterfaceNotInheritedByCurrentType:TLocalisedMessage(interfaceName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_INTERFACE_NOT_INHERITED_BY_CURRENT_TYPE, "Interface '{interfaceName}' is not inherited by the current type.", [TMessageArg.Create("interfaceName", interfaceName)])
	End Function
	Function BindingBoundMethodReceiverRequiresReferenceType:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_BOUND_METHOD_RECEIVER_REQUIRES_REFERENCE_TYPE, "Bound Method references currently support Type and Interface receivers; Struct receiver capture semantics are not yet defined.")
	End Function
	Function BindingNameNotResolvedAsValue:TLocalisedMessage(name:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_NAME_NOT_RESOLVED_AS_VALUE, "Name '{name}' could not be resolved as a value.", [TMessageArg.Create("name", name)])
	End Function
	Function BindingNamedCastRequiresOneExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_NAMED_CAST_REQUIRES_ONE_EXPRESSION, "A named type cast requires exactly one expression.")
	End Function
	Function BindingExplicitConversionNotAvailable:TLocalisedMessage(sourceType:String, targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_EXPLICIT_CONVERSION_NOT_AVAILABLE, "Type '{sourceType}' cannot be explicitly converted to '{targetType}'.", [TMessageArg.Create("sourceType", sourceType), TMessageArg.Create("targetType", targetType)])
	End Function
	Function BindingQualifiedSuperRequiresDefaultInterfaceMethod:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_QUALIFIED_SUPER_REQUIRES_DEFAULT_INTERFACE_METHOD, "Qualified Super can call only a Default Interface method body.")
	End Function
	Function BindingCannotInstantiateAbstractType:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CANNOT_INSTANTIATE_ABSTRACT_TYPE, "Cannot create an instance of abstract type '{typeName}'.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingRangeSlicingRequiresOneDimensionalArray:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RANGE_SLICING_REQUIRES_ONE_DIMENSIONAL_ARRAY, "Range slicing requires a one-dimensional heap Array.")
	End Function
	Function BindingRangeSlicingRejectsStaticArray:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RANGE_SLICING_REJECTS_STATIC_ARRAY, "Range slicing requires a one-dimensional heap Array; StaticArray values are not supported.")
	End Function
	Function BindingTypeHasNoApplicableIndexingOperator:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_TYPE_HAS_NO_APPLICABLE_INDEXING_OPERATOR, "Type '{typeName}' does not provide an applicable indexing operator.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingIndexExpressionRequiresUintConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_INDEX_EXPRESSION_REQUIRES_UINT_CONVERSION, "Type '{typeName}' is not valid for an index expression; conversion to UInt is required.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingSliceBoundRequiresIntConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_SLICE_BOUND_REQUIRES_INT_CONVERSION, "Type '{typeName}' is not valid for a slice bound; conversion to Int is required.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingTypeDoesNotSupportSlicing:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_TYPE_DOES_NOT_SUPPORT_SLICING, "Type '{typeName}' does not support slicing.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingRangeRequiresBrlRange:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RANGE_REQUIRES_BRL_RANGE, "Range expression syntax requires Import BRL.Range.")
	End Function
	Function BindingRangeEndpointRequiresIntConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_RANGE_ENDPOINT_REQUIRES_INT_CONVERSION, "Type '{typeName}' is not valid for a Range endpoint; conversion to Int is required.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingBoundMethodReferenceAmbiguousForTarget:TLocalisedMessage(targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_BOUND_METHOD_REFERENCE_AMBIGUOUS_FOR_TARGET, "Bound Method reference is ambiguous for target type '{targetType}'.", [TMessageArg.Create("targetType", targetType)])
	End Function
	Function BindingFunctionLiteralRequiresSuperStrict:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_REQUIRES_SUPER_STRICT, "Function literals require SuperStrict mode.")
	End Function
	Function BindingFunctionLiteralParameterCountMismatch:TLocalisedMessage(actualCount:Long, targetType:String, requiredCount:Long)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_COUNT_MISMATCH, "Function literal has {actualCount} parameters but target type '{targetType}' requires {requiredCount}.", [TMessageArg.CreateInt("actualCount", actualCount), TMessageArg.Create("targetType", targetType), TMessageArg.CreateInt("requiredCount", requiredCount)])
	End Function
	Function BindingFunctionLiteralParameterTypeMismatch:TLocalisedMessage(parameterName:String, actualType:String, targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_TYPE_MISMATCH, "Function literal parameter '{parameterName}' has type '{actualType}' but target requires '{targetType}'.", [TMessageArg.Create("parameterName", parameterName), TMessageArg.Create("actualType", actualType), TMessageArg.Create("targetType", targetType)])
	End Function
	Function BindingFunctionLiteralParameterRequiresVarMode:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETER_REQUIRES_VAR_MODE, "Function literal parameter '{parameterName}' must match the target's Var passing mode.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function BindingFunctionLiteralParametersRejectDefaults:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_PARAMETERS_REJECT_DEFAULTS, "Function literal parameters cannot declare default values.")
	End Function
	Function BindingFunctionLiteralReturnTypeMismatch:TLocalisedMessage(actualType:String, targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_FUNCTION_LITERAL_RETURN_TYPE_MISMATCH, "Function literal return type '{actualType}' does not match target return type '{targetType}'.", [TMessageArg.Create("actualType", actualType), TMessageArg.Create("targetType", targetType)])
	End Function
	Function BindingThinFunctionLiteralCannotCapture:TLocalisedMessage(name:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_THIN_FUNCTION_LITERAL_CANNOT_CAPTURE, "Thin Function literal cannot capture '{name}'; captured lexical state requires managed Closure support.", [TMessageArg.Create("name", name)])
	End Function
	Function BindingManagedClosureCannotCapture:TLocalisedMessage(name:String, reason:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_MANAGED_CLOSURE_CANNOT_CAPTURE, "Managed Closure cannot capture '{name}' in this phase: {reason}.", [TMessageArg.Create("name", name), TMessageArg.Create("reason", reason)])
	End Function
	Function BindingMemberNotResolved:TLocalisedMessage(memberName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_MEMBER_NOT_RESOLVED, "Member '{memberName}' could not be resolved.", [TMessageArg.Create("memberName", memberName)])
	End Function
	Function BindingGenericRoutineReferenceHasNoSpecialization:TLocalisedMessage(referenceName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_GENERIC_ROUTINE_REFERENCE_HAS_NO_SPECIALIZATION, "Generic routine reference '{referenceName}' has no specialization applicable to the supplied type arguments.", [TMessageArg.Create("referenceName", referenceName)])
	End Function
	Function BindingGenericRoutineReferenceIsAmbiguous:TLocalisedMessage(referenceName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_GENERIC_ROUTINE_REFERENCE_IS_AMBIGUOUS, "Generic routine reference '{referenceName}' is ambiguous between matching overloads.", [TMessageArg.Create("referenceName", referenceName)])
	End Function
	Function BindingDefaultConstructorInaccessible:TLocalisedMessage(typeName:String, visibility:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_DEFAULT_CONSTRUCTOR_INACCESSIBLE, "The default constructor for '{typeName}' is {visibility} and cannot be called from this scope.", [TMessageArg.Create("typeName", typeName), TMessageArg.Create("visibility", visibility)])
	End Function
	Function BindingImplicitConversionNotAvailable:TLocalisedMessage(sourceType:String, targetType:String, context:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_IMPLICIT_CONVERSION_NOT_AVAILABLE, "Type '{sourceType}' cannot be implicitly converted to '{targetType}' in {context}.", [TMessageArg.Create("sourceType", sourceType), TMessageArg.Create("targetType", targetType), TMessageArg.Create("context", context)])
	End Function
	Function BindingCannotCallAbstractFunction:TLocalisedMessage(signature:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CANNOT_CALL_ABSTRACT_FUNCTION, "Cannot call abstract Function {signature}.", [TMessageArg.Create("signature", signature)])
	End Function
	Function BindingRoutineUsedAsValue:TLocalisedMessage(routineKind:String, routineName:String, invocation:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ROUTINE_USED_AS_VALUE, "{routineKind} '{routineName}' is being used as a value rather than called.~nAdd parentheses to call it: {invocation}()", [TMessageArg.Create("routineKind", routineKind), TMessageArg.Create("routineName", routineName), TMessageArg.Create("invocation", invocation)])
	End Function
	Function BindingSymbolInaccessibleFromScope:TLocalisedMessage(category:String, qualifiedName:String, visibility:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_SYMBOL_INACCESSIBLE_FROM_SCOPE, "{category} '{qualifiedName}' is {visibility} and cannot be accessed from this scope.", [TMessageArg.Create("category", category), TMessageArg.Create("qualifiedName", qualifiedName), TMessageArg.Create("visibility", visibility)])
	End Function
	Function BindingGenericTypeQualifierNotResolved:TLocalisedMessage(qualifier:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_GENERIC_TYPE_QUALIFIER_NOT_RESOLVED, "Generic type qualifier '{qualifier}' could not be resolved as a type.", [TMessageArg.Create("qualifier", qualifier)])
	End Function
	Function BindingGenericTypeArgumentCountMismatch:TLocalisedMessage(typeName:String, expectedCount:Long, suppliedCount:Long)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_GENERIC_TYPE_ARGUMENT_COUNT_MISMATCH, "Generic type '{typeName}' expects {expectedCount} type argument(s), but {suppliedCount} were supplied.", [TMessageArg.Create("typeName", typeName), TMessageArg.CreateInt("expectedCount", expectedCount), TMessageArg.CreateInt("suppliedCount", suppliedCount)])
	End Function
	Function BindingAscRequiresStringConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ASC_REQUIRES_STRING_CONVERSION, "Type '{typeName}' cannot be converted to 'String' for Asc.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingChrRequiresIntConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CHR_REQUIRES_INT_CONVERSION, "Type '{typeName}' cannot be converted to 'Int' for Chr.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingStackAllocRequiresSizeTConversion:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_STACK_ALLOC_REQUIRES_SIZE_T_CONVERSION, "Type '{typeName}' cannot be converted to 'Size_T' for StackAlloc.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function BindingVarPtrRequiresWritableStorage:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_VAR_PTR_REQUIRES_WRITABLE_STORAGE, "VarPtr requires writable, addressable storage.")
	End Function
	Function BindingStandardRangeMissingBoundResolution:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_STANDARD_RANGE_MISSING_BOUND_RESOLUTION, "The standard Range type does not provide its required bound-resolution methods.")
	End Function
	Function BindingConstructorDelegationRequiresNewSyntax:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_REQUIRES_NEW_SYNTAX, "A constructor can only be delegated with New(...) or Super.New(...).")
	End Function
	Function BindingConstructorDelegationRequiresNewMethod:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_REQUIRES_NEW_METHOD, "Constructor delegation is only valid inside a New method.")
	End Function
	Function BindingConstructorDelegationMustBeFirst:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CONSTRUCTOR_DELEGATION_MUST_BE_FIRST, "Constructor delegation must be the first statement in a New method.")
	End Function
	Function BindingConstructorCannotDelegateToItself:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CONSTRUCTOR_CANNOT_DELEGATE_TO_ITSELF, "A constructor cannot delegate directly to itself.")
	End Function
	Function BindingIterationRequiresSupportedSource:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ITERATION_REQUIRES_SUPPORTED_SOURCE, "{operationName} requires an Array, String, StaticArray, IIterable, IIterator, or suitable ObjectEnumerator method.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function BindingIteratorFactoryReturnTypeUnusable:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ITERATOR_FACTORY_RETURN_TYPE_UNUSABLE, "{operationName} iterator factory does not return a usable iterator type.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function BindingIteratorMissingRequiredMethods:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ITERATOR_MISSING_REQUIRED_METHODS, "{operationName} iterator does not provide the required advance and current-value methods.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function BindingIteratorMethodReturnsInvalid:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_ITERATOR_METHOD_RETURNS_INVALID, "{operationName} iterator advance must return an integral value and its current-value method must return a value.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function BindingEachInDeconstructionRequiresTwoBindings:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_EACH_IN_DECONSTRUCTION_REQUIRES_TWO_BINDINGS, "EachIn deconstruction currently requires exactly two loop bindings for BRL.Blitz.IDeconstruct2<A, B>.")
	End Function
	Function BindingEachInElementRequiresDeconstruct2:TLocalisedMessage(elementType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_EACH_IN_ELEMENT_REQUIRES_DECONSTRUCT2, "EachIn element type '{elementType}' must implement BRL.Blitz.IDeconstruct2<A, B> for two loop bindings.", [TMessageArg.Create("elementType", elementType)])
	End Function
	Function BindingDeconstruct2RequiresMethodContract:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_DECONSTRUCT2_REQUIRES_METHOD_CONTRACT, "BRL.Blitz.IDeconstruct2<A, B> must provide Method Deconstruct(first:A Var, second:B Var).")
	End Function
	Function BindingEachInDeconstructionBindingTypeMismatch:TLocalisedMessage(bindingName:String, bindingType:String, componentIndex:Long, componentType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_EACH_IN_DECONSTRUCTION_BINDING_TYPE_MISMATCH, "EachIn binding '{bindingName}' has type '{bindingType}', but IDeconstruct2 component {componentIndex} has type '{componentType}'.", [TMessageArg.Create("bindingName", bindingName), TMessageArg.Create("bindingType", bindingType), TMessageArg.CreateInt("componentIndex", componentIndex), TMessageArg.Create("componentType", componentType)])
	End Function
	Function BindingEachInElementConversionNotAvailable:TLocalisedMessage(elementType:String, targetDescription:String, targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_EACH_IN_ELEMENT_CONVERSION_NOT_AVAILABLE, "EachIn element type '{elementType}' cannot be converted to {targetDescription} of type '{targetType}'.", [TMessageArg.Create("elementType", elementType), TMessageArg.Create("targetDescription", targetDescription), TMessageArg.Create("targetType", targetType)])
	End Function
	Function DataDuplicateLabel:TLocalisedMessage(labelName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_DUPLICATE_LABEL, "Duplicate data label '{labelName}'.", [TMessageArg.Create("labelName", labelName)])
	End Function
	Function DataItemRequiresConstantNumericOrString:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_ITEM_REQUIRES_CONSTANT_NUMERIC_OR_STRING, "Data items must be constant numeric or string expressions.")
	End Function
	Function DataItemMissingBetweenSeparators:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_ITEM_MISSING_BETWEEN_SEPARATORS, "A data item is missing between separators.")
	End Function
	Function DataRestoreRequiresLabelName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_RESTORE_REQUIRES_LABEL_NAME, "RestoreData requires a data-label name.")
	End Function
	Function DataLabelNotFound:TLocalisedMessage(labelName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_LABEL_NOT_FOUND, "Data label '{labelName}' could not be found.", [TMessageArg.Create("labelName", labelName)])
	End Function
	Function DataReadTargetRequiresWritableStorage:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_READ_TARGET_REQUIRES_WRITABLE_STORAGE, "ReadData target must be a writable variable, field, or indexed element.")
	End Function
	Function DataReadTargetTypeUnsupported:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_READ_TARGET_TYPE_UNSUPPORTED, "ReadData does not support target type '{typeName}'.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function DataReadTargetMissingBetweenSeparators:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DATA_READ_TARGET_MISSING_BETWEEN_SEPARATORS, "A ReadData target is missing between separators.")
	End Function
	Function ConstantDefinitionCycle:TLocalisedMessage(constantName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_DEFINITION_CYCLE, "Constant definition cycle involving '{constantName}'.", [TMessageArg.Create("constantName", constantName)])
	End Function
	Function ConstantRequiresInitializer:TLocalisedMessage(constantName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_REQUIRES_INITIALIZER, "Const '{constantName}' requires a constant initializer.", [TMessageArg.Create("constantName", constantName)])
	End Function
	Function ConstantImportedEnumValueUnusable:TLocalisedMessage(valueName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_IMPORTED_ENUM_VALUE_UNUSABLE, "Imported enum value '{valueName}' has no usable integral constant.", [TMessageArg.Create("valueName", valueName)])
	End Function
	Function ConstantEnumValueOutOfRange:TLocalisedMessage(valueName:String, underlyingType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_ENUM_VALUE_OUT_OF_RANGE, "Enum value '{valueName}' is outside the range of '{underlyingType}'.", [TMessageArg.Create("valueName", valueName), TMessageArg.Create("underlyingType", underlyingType)])
	End Function
	Function ConstantEnumValueRequiresIntegralExpression:TLocalisedMessage(valueName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_ENUM_VALUE_REQUIRES_INTEGRAL_EXPRESSION, "Enum value '{valueName}' requires an integral constant expression.", [TMessageArg.Create("valueName", valueName)])
	End Function
	Function ConstantValueOutOfRange:TLocalisedMessage(targetType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONSTANT_VALUE_OUT_OF_RANGE, "Constant value is outside the range of '{targetType}'.", [TMessageArg.Create("targetType", targetType)])
	End Function
	Function CompileTimeEnumConstantValueInvalid:TLocalisedMessage(value:Long, enumType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_ENUM_CONSTANT_VALUE_INVALID, "The value {value} is not valid for Enum '{enumType}'.", [TMessageArg.CreateInt("value", value), TMessageArg.Create("enumType", enumType)])
	End Function
	Function CompileTimeStaticArrayElementTypeUnsupported:TLocalisedMessage(elementType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_ELEMENT_TYPE_UNSUPPORTED, "StaticArray element type '{elementType}' must be numeric, an Enum, a Pointer, a managed reference, or a Struct.", [TMessageArg.Create("elementType", elementType)])
	End Function
	Function CompileTimeStaticArrayLengthRequiresIntegralConstant:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_LENGTH_REQUIRES_INTEGRAL_CONSTANT, "StaticArray length must be an integral constant.")
	End Function
	Function CompileTimeStaticArrayLengthOutOfRange:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_STATIC_ARRAY_LENGTH_OUT_OF_RANGE, "StaticArray length must be between 1 and 2147483647.")
	End Function
	Function CompileTimeParameterDefaultRequiresConstant:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_PARAMETER_DEFAULT_REQUIRES_CONSTANT, "Default value for parameter '{parameterName}' must be constant.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function CompileTimeParameterConstantDefaultIncompatible:TLocalisedMessage(parameterName:String, parameterType:String, routineName:String, parameterIndex:Long, declaredType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_PARAMETER_CONSTANT_DEFAULT_INCOMPATIBLE, "Constant default for parameter '{parameterName}' is incompatible with '{parameterType}' in routine '{routineName}' at parameter {parameterIndex} (declared type '{declaredType}').", [TMessageArg.Create("parameterName", parameterName), TMessageArg.Create("parameterType", parameterType), TMessageArg.Create("routineName", routineName), TMessageArg.CreateInt("parameterIndex", parameterIndex), TMessageArg.Create("declaredType", declaredType)])
	End Function
	Function CompileTimeSemanticParameterMissing:TLocalisedMessage(routineName:String, parameterIndex:Long, syntaxName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_SEMANTIC_PARAMETER_MISSING, "Internal semantic parameter mismatch in routine '{routineName}': syntax parameter {parameterIndex} ('{syntaxName}') has no semantic parameter.", [TMessageArg.Create("routineName", routineName), TMessageArg.CreateInt("parameterIndex", parameterIndex), TMessageArg.Create("syntaxName", syntaxName)])
	End Function
	Function CompileTimeSemanticParameterIdentityMismatch:TLocalisedMessage(routineName:String, parameterIndex:Long, syntaxName:String, declaredType:String, semanticName:String, semanticType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_COMPILE_TIME_SEMANTIC_PARAMETER_IDENTITY_MISMATCH, "Internal semantic parameter mismatch in routine '{routineName}' at parameter {parameterIndex}: syntax '{syntaxName}' (declared type '{declaredType}'), semantic symbol '{semanticName}' (type '{semanticType}').", [TMessageArg.Create("routineName", routineName), TMessageArg.CreateInt("parameterIndex", parameterIndex), TMessageArg.Create("syntaxName", syntaxName), TMessageArg.Create("declaredType", declaredType), TMessageArg.Create("semanticName", semanticName), TMessageArg.Create("semanticType", semanticType)])
	End Function
	Function ControlFlowImplicitDefaultReturnReachable:TLocalisedMessage(routineName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONTROL_FLOW_IMPLICIT_DEFAULT_RETURN_REACHABLE, "Routine '{routineName}' can reach its implicit default return.", [TMessageArg.Create("routineName", routineName)])
	End Function
	Function ControlFlowLoopControlRequiresLoop:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONTROL_FLOW_LOOP_CONTROL_REQUIRES_LOOP, "{operationName} can be used only inside a loop.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function ControlFlowLoopControlRequiresLabelName:TLocalisedMessage(operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONTROL_FLOW_LOOP_CONTROL_REQUIRES_LABEL_NAME, "{operationName} requires a loop-label name.", [TMessageArg.Create("operationName", operationName)])
	End Function
	Function ControlFlowLoopLabelNotFound:TLocalisedMessage(labelName:String, operationName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONTROL_FLOW_LOOP_LABEL_NOT_FOUND, "Loop label '{labelName}' could not be found for {operationName}.", [TMessageArg.Create("labelName", labelName), TMessageArg.Create("operationName", operationName)])
	End Function
	Function ControlFlowUnreachableStatement:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_CONTROL_FLOW_UNREACHABLE_STATEMENT, "Unreachable statement.")
	End Function
	Function InheritancePublicContractExposesHiddenType:TLocalisedMessage(publicKind:String, publicName:String, visibility:String, hiddenKind:String, hiddenName:String, role:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_PUBLIC_CONTRACT_EXPOSES_HIDDEN_TYPE, "Public {publicKind} '{publicName}' exposes {visibility} {hiddenKind} '{hiddenName}' through its {role}.", [TMessageArg.Create("publicKind", publicKind), TMessageArg.Create("publicName", publicName), TMessageArg.Create("visibility", visibility), TMessageArg.Create("hiddenKind", hiddenKind), TMessageArg.Create("hiddenName", hiddenName), TMessageArg.Create("role", role)])
	End Function
	Function InheritanceOverrideMethodNotFound:TLocalisedMessage(methodName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_OVERRIDE_METHOD_NOT_FOUND, "Method '{methodName}' is marked Override but does not override a method from a base type.", [TMessageArg.Create("methodName", methodName)])
	End Function
	Function InheritanceOverrideReducesVisibility:TLocalisedMessage(methodName:String, inheritedVisibility:String, declaredVisibility:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_OVERRIDE_REDUCES_VISIBILITY, "Method '{methodName}' cannot reduce inherited visibility from '{inheritedVisibility}' to '{declaredVisibility}'.", [TMessageArg.Create("methodName", methodName), TMessageArg.Create("inheritedVisibility", inheritedVisibility), TMessageArg.Create("declaredVisibility", declaredVisibility)])
	End Function
	Function InheritanceDefaultRequiresInterfaceInstanceMethod:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_DEFAULT_REQUIRES_INTERFACE_INSTANCE_METHOD, "Default is valid only on an instance Method declared by an Interface.")
	End Function
	Function InheritanceInterfaceDefaultCannotBeAbstract:TLocalisedMessage(methodName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_INTERFACE_DEFAULT_CANNOT_BE_ABSTRACT, "Interface method '{methodName}' cannot be both Default and Abstract.", [TMessageArg.Create("methodName", methodName)])
	End Function
	Function InheritanceGenericConstraintParameterUndeclared:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_PARAMETER_UNDECLARED, "Generic constraint refers to undeclared type parameter '{parameterName}'.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function InheritanceGenericConstraintDuplicateClause:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_DUPLICATE_CLAUSE, "Type parameter '{parameterName}' has more than one constraint clause.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function InheritanceGenericConstraintBoundInvalid:TLocalisedMessage(boundType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_GENERIC_CONSTRAINT_BOUND_INVALID, "Generic constraint bound '{boundType}' is not a declared reference type or type parameter.", [TMessageArg.Create("boundType", boundType)])
	End Function
	Function InheritanceStructCannotInherit:TLocalisedMessage(structName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_STRUCT_CANNOT_INHERIT, "Struct '{structName}' cannot extend or implement another type.", [TMessageArg.Create("structName", structName)])
	End Function
	Function InheritanceTypeAllowsSingleBase:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_TYPE_ALLOWS_SINGLE_BASE, "Type '{typeName}' can extend only one base type.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function InheritanceInterfaceBaseRequiresInterface:TLocalisedMessage(interfaceName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_INTERFACE_BASE_REQUIRES_INTERFACE, "Interface '{interfaceName}' can extend only interfaces.", [TMessageArg.Create("interfaceName", interfaceName)])
	End Function
	Function InheritanceExternalManagedInterfaceMismatch:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_EXTERNAL_MANAGED_INTERFACE_MISMATCH, "External and managed interfaces cannot extend one another.")
	End Function
	Function InheritanceTypeBaseRequiresReferenceType:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_TYPE_BASE_REQUIRES_REFERENCE_TYPE, "Type '{typeName}' can extend only another reference type.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function InheritanceFinalTypeCannotBeExtended:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_FINAL_TYPE_CANNOT_BE_EXTENDED, "Type '{typeName}' is Final and cannot be extended.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function InheritanceInterfaceCannotUseImplements:TLocalisedMessage(interfaceName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_INTERFACE_CANNOT_USE_IMPLEMENTS, "Interface '{interfaceName}' cannot use Implements; extend interfaces instead.", [TMessageArg.Create("interfaceName", interfaceName)])
	End Function
	Function InheritanceImplementsTargetNotInterface:TLocalisedMessage(targetName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_IMPLEMENTS_TARGET_NOT_INTERFACE, "'{targetName}' is not an interface.", [TMessageArg.Create("targetName", targetName)])
	End Function
	Function InheritanceInterfaceSelectorReturnTypesIncompatible:TLocalisedMessage(typeName:String, methodName:String, firstReturnType:String, secondReturnType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_INTERFACE_SELECTOR_RETURN_TYPES_INCOMPATIBLE, "Type '{typeName}' inherits Interface method selector '{methodName}' with incompatible return types '{firstReturnType}' and '{secondReturnType}'.", [TMessageArg.Create("typeName", typeName), TMessageArg.Create("methodName", methodName), TMessageArg.Create("firstReturnType", firstReturnType), TMessageArg.Create("secondReturnType", secondReturnType)])
	End Function
	Function InheritanceUnrelatedInterfaceDefaults:TLocalisedMessage(typeName:String, origins:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_UNRELATED_INTERFACE_DEFAULTS, "Type '{typeName}' inherits unrelated default Interface methods {origins}; declare an overriding Method to resolve the conflict.", [TMessageArg.Create("typeName", typeName), TMessageArg.Create("origins", origins)])
	End Function
	Function InheritanceInterfaceListedMoreThanOnce:TLocalisedMessage(interfaceType:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_INTERFACE_LISTED_MORE_THAN_ONCE, "Interface '{interfaceType}' is listed more than once.", [TMessageArg.Create("interfaceType", interfaceType)])
	End Function
	Function InheritanceCycle:TLocalisedMessage(typeName:String, relatedTypeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_CYCLE, "Inheritance cycle involving '{typeName}' and '{relatedTypeName}'.", [TMessageArg.Create("typeName", typeName), TMessageArg.Create("relatedTypeName", relatedTypeName)])
	End Function
	Function InheritanceTypeArgumentConstraintUnsatisfied:TLocalisedMessage(argumentType:String, requiredType:String, parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INHERITANCE_TYPE_ARGUMENT_CONSTRAINT_UNSATISFIED, "Type argument '{argumentType}' does not satisfy constraint '{requiredType}' for '{parameterName}'.", [TMessageArg.Create("argumentType", argumentType), TMessageArg.Create("requiredType", requiredType), TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function TypeResolutionSymbolRequiresExplicitType:TLocalisedMessage(symbolKind:String, symbolName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_SYMBOL_REQUIRES_EXPLICIT_TYPE, "{symbolKind} '{symbolName}' requires an explicit type in SuperStrict code.", [TMessageArg.Create("symbolKind", symbolKind), TMessageArg.Create("symbolName", symbolName)])
	End Function
	Function TypeResolutionCallingConventionUnrecognized:TLocalisedMessage(callingConvention:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CALLING_CONVENTION_UNRECOGNIZED, "Unrecognized calling convention '{callingConvention}'.", [TMessageArg.Create("callingConvention", callingConvention)])
	End Function
	Function TypeResolutionCallableParameterRequiresExplicitType:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CALLABLE_PARAMETER_REQUIRES_EXPLICIT_TYPE, "Callable parameter '{parameterName}' requires an explicit type in SuperStrict code.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function TypeResolutionRoutineConstraintParameterUndeclared:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_ROUTINE_CONSTRAINT_PARAMETER_UNDECLARED, "Generic constraint refers to undeclared routine type parameter '{parameterName}'.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function TypeResolutionClosureRequiresSuperstrict:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_REQUIRES_SUPERSTRICT, "Closure types require SuperStrict mode.")
	End Function
	Function TypeResolutionClosureRequiresExplicitSignature:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_REQUIRES_EXPLICIT_SIGNATURE, "The compiler-intrinsic Closure type requires an explicit signature, for example Closure<Int(value:Int)> or Closure<()>.")
	End Function
	Function TypeResolutionClosureParameterRequiresNameAndType:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_PARAMETER_REQUIRES_NAME_AND_TYPE, "Closure parameters require an explicit name and type.")
	End Function
	Function TypeResolutionClosureSignatureRejectsDefault:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_SIGNATURE_REJECTS_DEFAULT, "Closure signatures cannot declare default parameter values.")
	End Function
	Function TypeResolutionClosureSignatureRejectsNativeCallingConvention:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_CLOSURE_SIGNATURE_REJECTS_NATIVE_CALLING_CONVENTION, "Closure signatures cannot specify a native calling convention.")
	End Function
	Function TypeResolutionAmbiguousTypeName:TLocalisedMessage(typeName:String, candidates:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_AMBIGUOUS_TYPE_NAME, "Type name '{typeName}' is ambiguous. Candidates:{candidates}", [TMessageArg.Create("typeName", typeName), TMessageArg.Create("candidates", candidates)])
	End Function
	Function TypeResolutionTypeParameterRejectsTypeArguments:TLocalisedMessage(parameterName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_TYPE_PARAMETER_REJECTS_TYPE_ARGUMENTS, "Type parameter '{parameterName}' cannot have type arguments.", [TMessageArg.Create("parameterName", parameterName)])
	End Function
	Function TypeResolutionTypeNotResolved:TLocalisedMessage(typeName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_TYPE_RESOLUTION_TYPE_NOT_RESOLVED, "Type '{typeName}' could not be resolved in the available scopes.", [TMessageArg.Create("typeName", typeName)])
	End Function
	Function SnapshotDependenciesUnresolved:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_DEPENDENCIES_UNRESOLVED, "The compiler could not resolve source and module dependencies.")
	End Function
	Function SnapshotImplicitRuntimeInterfaceUnavailable:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_IMPLICIT_RUNTIME_INTERFACE_UNAVAILABLE, "Compiler interface for implicit runtime module 'brl.blitz' is unavailable.")
	End Function
	Function SnapshotImplicitApplicationInterfaceUnavailable:TLocalisedMessage(moduleName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_IMPLICIT_APPLICATION_INTERFACE_UNAVAILABLE, "Compiler interface for implicit application module '{moduleName}' is unavailable.", [TMessageArg.Create("moduleName", moduleName)])
	End Function
	Function SnapshotCoreInterfaceMissing:TLocalisedMessage(targetPlatform:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_CORE_INTERFACE_MISSING, "The core class interface is missing for target '{targetPlatform}'.", [TMessageArg.Create("targetPlatform", targetPlatform)])
	End Function
	Function SnapshotIncludeCycle:TLocalisedMessage(includedPath:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_INCLUDE_CYCLE, "Include cycle reaches '{includedPath}'.", [TMessageArg.Create("includedPath", includedPath)])
	End Function
	Function SnapshotIncludedSourceNotFound:TLocalisedMessage(sourcePath:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_INCLUDED_SOURCE_NOT_FOUND, "Included source '{sourcePath}' could not be found.", [TMessageArg.Create("sourcePath", sourcePath)])
	End Function
	Function SnapshotCompilerInterfaceUnavailable:TLocalisedMessage(targetName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_COMPILER_INTERFACE_UNAVAILABLE, "Compiler interface for '{targetName}' is unavailable.", [TMessageArg.Create("targetName", targetName)])
	End Function
	Function SnapshotGenericTemplateFormatUnsupported:TLocalisedMessage(recordName:String, formatVersion:Long)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_FORMAT_UNSUPPORTED, "Generic template reference for '{recordName}' uses unsupported format {formatVersion}.", [TMessageArg.Create("recordName", recordName), TMessageArg.CreateInt("formatVersion", formatVersion)])
	End Function
	Function SnapshotGenericTemplateArtifactUnavailable:TLocalisedMessage(artifactReference:String, recordName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_ARTIFACT_UNAVAILABLE, "Generic template artifact '{artifactReference}' for '{recordName}' is unavailable from the compiler interface.", [TMessageArg.Create("artifactReference", artifactReference), TMessageArg.Create("recordName", recordName)])
	End Function
	Function SnapshotGenericTemplateArtifactInvalid:TLocalisedMessage(artifactPath:String, recordName:String, detail:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_ARTIFACT_INVALID, "Generic template artifact '{artifactPath}' for '{recordName}' is invalid.{detail}", [TMessageArg.Create("artifactPath", artifactPath), TMessageArg.Create("recordName", recordName), TMessageArg.Create("detail", detail)])
	End Function
	Function SnapshotGenericTemplateIdentityMismatch:TLocalisedMessage(artifactIdentity:String, interfaceIdentity:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_IDENTITY_MISMATCH, "Generic template artifact identity '{artifactIdentity}' does not match interface identity '{interfaceIdentity}'.", [TMessageArg.Create("artifactIdentity", artifactIdentity), TMessageArg.Create("interfaceIdentity", interfaceIdentity)])
	End Function
	Function SnapshotGenericTemplateLanguageRevisionMismatch:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SNAPSHOT_GENERIC_TEMPLATE_LANGUAGE_REVISION_MISMATCH, "Generic template artifact language revision does not match its interface reference.")
	End Function
	Function LexerNumericExponentRequiresDigit:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_LEXER_NUMERIC_EXPONENT_REQUIRES_DIGIT, "A numeric exponent requires at least one digit.")
	End Function
	Function LexerUnterminatedMultilineString:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_LEXER_UNTERMINATED_MULTILINE_STRING, "Unterminated multiline string literal.")
	End Function
	Function LexerUnterminatedString:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_LEXER_UNTERMINATED_STRING, "Unterminated string literal.")
	End Function
	Function LexerBadStringEscape:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_LEXER_BAD_STRING_ESCAPE, "Bad escape sequence in string literal.")
	End Function
	Function LexerUnterminatedRemComment:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_LEXER_UNTERMINATED_REM_COMMENT, "Unterminated Rem comment.")
	End Function
	Function ParserExpectedConditionalRegionEnd:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CONDITIONAL_REGION_END, "Expected '?' to end conditional region.")
	End Function
	Function ParserInferredLocalSyntaxRequired:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_INFERRED_LOCAL_SYNTAX_REQUIRED, "The ':=' syntax is only valid in an inferred Local declaration; use '=' for assignment.")
	End Function
	Function ParserExpectedRoutineName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_ROUTINE_NAME, "Expected a routine name.")
	End Function
	Function ParserInterfaceMethodRejectsBody:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_INTERFACE_METHOD_REJECTS_BODY, "Interface method declarations cannot contain a body.")
	End Function
	Function ParserExpectedTypeName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_TYPE_NAME, "Expected a type name.")
	End Function
	Function ParserExpectedBlockEndBeforeEof:TLocalisedMessage(blockKind:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_BLOCK_END_BEFORE_EOF, "Expected 'End {blockKind}' before end of file.", [TMessageArg.Create("blockKind", blockKind)])
	End Function
	Function ParserMismatchedBlockEnd:TLocalisedMessage(expectedKind:String, terminator:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_MISMATCHED_BLOCK_END, "Expected 'End {expectedKind}' but found '{terminator}'.", [TMessageArg.Create("expectedKind", expectedKind), TMessageArg.Create("terminator", terminator)])
	End Function
	Function ParserExpectedImportTarget:TLocalisedMessage(keyword:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_IMPORT_TARGET, "Expected a module name or file path after '{keyword}'.", [TMessageArg.Create("keyword", keyword)])
	End Function
	Function ParserUnexpectedTokenAfterImportPath:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_IMPORT_PATH, "Unexpected token '{token}' after import file path.", [TMessageArg.Create("token", token)])
	End Function
	Function ParserExpectedIncludePath:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_INCLUDE_PATH, "Expected a quoted source path after 'Include'.")
	End Function
	Function ParserUnexpectedTokenAfterIncludePath:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_INCLUDE_PATH, "Unexpected token '{token}' after include path.", [TMessageArg.Create("token", token)])
	End Function
	Function ParserExpectedExpressionAfterYieldFrom:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_YIELD_FROM, "Expected an expression after 'Yield From'.")
	End Function
	Function ParserExpectedExpressionAfterYield:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_YIELD, "Expected an expression after 'Yield'.")
	End Function
	Function ParserExpectedExpressionAfterThrow:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_EXPRESSION_AFTER_THROW, "Expected an expression after 'Throw'.")
	End Function
	Function ParserExpectedIntegerVariableAfterRelease:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_INTEGER_VARIABLE_AFTER_RELEASE, "Expected an integer variable after 'Release'.")
	End Function
	Function ParserDefdataRequiresValue:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_DEFDATA_REQUIRES_VALUE, "DefData requires at least one value.")
	End Function
	Function ParserRestoredataRequiresLabel:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_RESTOREDATA_REQUIRES_LABEL, "RestoreData requires a data label.")
	End Function
	Function ParserExpectedConditionAfterAssert:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CONDITION_AFTER_ASSERT, "Expected a condition after 'Assert'.")
	End Function
	Function ParserExpectedAssertMessage:TLocalisedMessage(separator:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_ASSERT_MESSAGE, "Expected a message after '{separator}'.", [TMessageArg.Create("separator", separator)])
	End Function
	Function ParserInferenceRequiresLocal:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_INFERENCE_REQUIRES_LOCAL, "Type inference with ':=' is only valid for Local declarations.")
	End Function
	Function ParserInferredLocalRequiresSingleDeclarator:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_INFERRED_LOCAL_REQUIRES_SINGLE_DECLARATOR, "An inferred Local declaration must contain exactly one declarator.")
	End Function
	Function ParserExpectedVariableName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_VARIABLE_NAME, "Expected a variable name.")
	End Function
	Function ParserInferredLocalRequiresInitializer:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_INFERRED_LOCAL_REQUIRES_INITIALIZER, "An inferred Local declaration requires an initializer after ':='.")
	End Function
	Function ParserStaticArrayRequiresBracketedLength:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_STATIC_ARRAY_REQUIRES_BRACKETED_LENGTH, "StaticArray declaration requires a fixed length in brackets.")
	End Function
	Function ParserStaticArrayRequiresLengthExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_STATIC_ARRAY_REQUIRES_LENGTH_EXPRESSION, "StaticArray declaration requires a fixed length expression.")
	End Function
	Function ParserExpectedCaseValueAfterComma:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CASE_VALUE_AFTER_COMMA, "Expected a Case value after ','.")
	End Function
	Function ParserExpectedCaseValue:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CASE_VALUE, "Expected a Case value.")
	End Function
	Function ParserExpectedParenthesisInFunctionLiteral:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_PARENTHESIS_IN_FUNCTION_LITERAL, "Expected '(' in Function literal.")
	End Function
	Function ParserExpectedCloseParenthesisInFunctionLiteral:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_EXPECTED_CLOSE_PARENTHESIS_IN_FUNCTION_LITERAL, "Expected ')' in Function literal.")
	End Function
	Function ParserUnexpectedTokenAfterFunctionLiteralParameters:TLocalisedMessage(token:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_PARSER_UNEXPECTED_TOKEN_AFTER_FUNCTION_LITERAL_PARAMETERS, "Unexpected token '{token}' after Function literal parameters.", [TMessageArg.Create("token", token)])
	End Function
	Function SignatureExpectedGenericParameterEnd:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_EXPECTED_GENERIC_PARAMETER_END, "Expected '>' after routine generic parameters.")
	End Function
	Function SignatureExpectedRoutineParenthesis:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_EXPECTED_ROUTINE_PARENTHESIS, "Expected '(' in routine declaration.")
	End Function
	Function SignatureExpectedRoutineCloseParenthesis:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_EXPECTED_ROUTINE_CLOSE_PARENTHESIS, "Expected ')' in routine declaration.")
	End Function
	Function SignatureExpectedParameterName:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_EXPECTED_PARAMETER_NAME, "Expected a parameter name.")
	End Function
	Function SignatureStaticArrayParameterRequiresBracketedLength:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_STATIC_ARRAY_PARAMETER_REQUIRES_BRACKETED_LENGTH, "StaticArray parameter requires a fixed length in brackets.")
	End Function
	Function SignatureStaticArrayParameterRequiresLengthExpression:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_STATIC_ARRAY_PARAMETER_REQUIRES_LENGTH_EXPRESSION, "StaticArray parameter requires a fixed length expression.")
	End Function
	Function SignatureExpectedCallableCloseParenthesis:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_SIGNATURE_EXPECTED_CALLABLE_CLOSE_PARENTHESIS, "Expected ')' in callable type.")
	End Function
	Function DeclarationDuplicate:TLocalisedMessage(symbolKind:String, symbolName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DECLARATION_DUPLICATE, "Duplicate {symbolKind} declaration '{symbolName}'.", [TMessageArg.Create("symbolKind", symbolKind), TMessageArg.Create("symbolName", symbolName)])
	End Function
	Function DeclarationNomangleRequiresFunction:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DECLARATION_NOMANGLE_REQUIRES_FUNCTION, "Only functions can specify NoMangle.")
	End Function
	Function DeclarationNomangleOverloadConflict:TLocalisedMessage(routineName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_DECLARATION_NOMANGLE_OVERLOAD_CONFLICT, "NoMangle routine '{routineName}' conflicts with another overload.", [TMessageArg.Create("routineName", routineName)])
	End Function
	Function MetadataExpectedKey:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_METADATA_EXPECTED_KEY, "Expected a metadata key.")
	End Function
	Function MetadataExpectedLiteralValue:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_METADATA_EXPECTED_LITERAL_VALUE, "Expected a literal metadata value after '='.")
	End Function
	Function MetadataDuplicateKey:TLocalisedMessage(key:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_METADATA_DUPLICATE_KEY, "Duplicate metadata key '{key}'.", [TMessageArg.Create("key", key)])
	End Function
	Function MetadataExpectedCloseBrace:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_METADATA_EXPECTED_CLOSE_BRACE, "Expected '}}' after declaration metadata.")
	End Function
	Function InterfaceUnterminatedRecord:TLocalisedMessage(recordKind:String, recordName:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INTERFACE_UNTERMINATED_RECORD, "Unterminated {recordKind} record '{recordName}'.", [TMessageArg.Create("recordKind", recordKind), TMessageArg.Create("recordName", recordName)])
	End Function
	Function InterfaceGenericTemplateRequiresDeclaration:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INTERFACE_GENERIC_TEMPLATE_REQUIRES_DECLARATION, "Generic template reference does not follow a Type, Function, or Method record.")
	End Function
	Function InterfaceGenericTemplateReferenceInvalid:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_INTERFACE_GENERIC_TEMPLATE_REFERENCE_INVALID, "Generic template reference requires format, identity, revision, artifact and language revision.")
	End Function
	Function BindingDynamicNewInstanceDeprecated:TLocalisedMessage()
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_DYNAMIC_NEW_INSTANCE_DEPRECATED, "Use of New <Object instance> is deprecated, and support will be removed in a future update.")
	End Function
	Function BindingCallAmbiguous:TLocalisedMessage(callName:String, candidates:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_CALL_AMBIGUOUS, "Call '{callName}' is ambiguous between applicable overloads.{candidates}", [TMessageArg.Create("callName", callName), TMessageArg.Create("candidates", candidates)])
	End Function
	Function BindingNoApplicableOverload:TLocalisedMessage(callName:String, argumentTypes:String, candidates:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_NO_APPLICABLE_OVERLOAD, "No applicable overload was found for call '{callName}'.~~nArgument types: ({argumentTypes}){candidates}", [TMessageArg.Create("callName", callName), TMessageArg.Create("argumentTypes", argumentTypes), TMessageArg.Create("candidates", candidates)])
	End Function
	Function BindingVariableAssignedToItself:TLocalisedMessage(variableName:String, suggestion:String)
		Return TLocalisedMessage.Create("language", LANGUAGE_MSG_BINDING_VARIABLE_ASSIGNED_TO_ITSELF, "Variable '{variableName}' is assigned to itself.{suggestion}", [TMessageArg.Create("variableName", variableName), TMessageArg.Create("suggestion", suggestion)])
	End Function
End Type
